version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: gestionale_ui_nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.local.conf:/etc/nginx/nginx.conf:ro
    networks:
      - local_ui_net

networks:
  local_ui_net:
    driver: bridge