version: "3.8"

name: gestionale-energia

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=admin@gmgestionale.cloud
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --accesslog=true
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/letsencrypt
    networks:
      - proxy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gestionale-energia-app:latest
    container_name: gestionale-energia-app
    environment:
      NODE_ENV: production
      PORT: 3001
      FRONTEND_URL: https://gmgestionale.cloud
      BACKEND_URL: https://gmgestionale.cloud
      IS_DOCKER: "true"
      # Database - Configura questi valori
      DB_HOST: ${DB_HOST:-localhost}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-gestionale_energia}
      # JWT
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this}
      # Email (opzionale)
      BREVO_API_KEY: ${BREVO_API_KEY:-}
      EMAIL_FROM: ${EMAIL_FROM:-noreply@gmgestionale.cloud}
    restart: unless-stopped
    expose:
      - "3001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gmgestionale.rule=Host(`gmgestionale.cloud`,`www.gmgestionale.cloud`)"
      - "traefik.http.routers.gmgestionale.entrypoints=websecure"
      - "traefik.http.routers.gmgestionale.tls.certresolver=le"
      - "traefik.http.services.gmgestionale.loadbalancer.server.port=3001"
      # Redirect www to non-www
      - "traefik.http.middlewares.redirect-www.redirectregex.regex=^https://www\\.gmgestionale\\.cloud/(.*)"
      - "traefik.http.middlewares.redirect-www.redirectregex.replacement=https://gmgestionale.cloud/$${1}"
      - "traefik.http.routers.gmgestionale.middlewares=redirect-www"
    networks:
      - proxy

volumes:
  traefik-certs:
    driver: local

networks:
  proxy:
    driver: bridge